/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import java.util.logging.*;
/**
 *
 * @author BLABPC23
 */
public class View_Clients extends javax.swing.JPanel {
    ViewMain viewMain = new ViewMain();
    DefaultTableModel modelTable;
    mysql.Conexion con = new mysql.Conexion();

    /**
     * Creates new form View_Clients
     */
    public View_Clients() {
        modelTable = new DefaultTableModel(null, getColumnas());
        setFilas();
        initComponents();
    }
    private String[] getColumnas() {
        String columna[] = new String[]{"id_cliente", "Nombre", "Apellido Paterno", "Apellido Materno", "Telefono", "E-mail", "RFC", "Calle", "Numero", "Colonia", "Ciudad", "Estado"};
        return columna;
    }

    private void setFilas() {
        try {
            String sql = "Select * from clientes";
            PreparedStatement us = con.conexion().prepareStatement(sql);
            Object datos[] = new Object[12];
            ResultSet res = us.executeQuery();

            while (res.next()) {
                for (int i = 0; i < 12; i++) {
                    datos[i] = res.getObject(i + 1);
                }
                modelTable.addRow(datos);
            }
        } catch (SQLException ex) {
            Logger.getLogger(View_Clients.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jbt_Add = new javax.swing.JButton();
        Jbt_Options = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_Sandwich = new javax.swing.JLabel();

        Jbt_Add.setText("Agregar");
        Jbt_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbt_AddActionPerformed(evt);
            }
        });

        Jbt_Options.setText("Opciones");
        Jbt_Options.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Jbt_OptionsMouseClicked(evt);
            }
        });

        jTable2.setModel(modelTable);
        jScrollPane1.setViewportView(jTable2);

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel1.setText("Clientes");

        jLabel_Sandwich.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/sandwich.png"))); // NOI18N
        jLabel_Sandwich.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_SandwichMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(271, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(274, 274, 274))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Sandwich)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_Sandwich)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Jbt_Add)
                    .addComponent(Jbt_Options))
                .addGap(265, 265, 265))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(Jbt_Add)
                .addGap(18, 18, 18)
                .addComponent(Jbt_Options)
                .addGap(118, 118, 118))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Jbt_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbt_AddActionPerformed
        // TODO add your handling code here:
        View_Add JFrame = new View_Add();
        JFrame.setVisible(true);
    }//GEN-LAST:event_Jbt_AddActionPerformed

    private void Jbt_OptionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jbt_OptionsMouseClicked
        // TODO add your handling code here:
        View_Options JFrame = new View_Options();
        JFrame.setVisible(true);
    }//GEN-LAST:event_Jbt_OptionsMouseClicked

    private void jLabel_SandwichMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_SandwichMouseClicked
        // TODO add your handling code here:
        viewMain.setVisible(true);
    }//GEN-LAST:event_jLabel_SandwichMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Jbt_Add;
    public javax.swing.JButton Jbt_Options;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel_Sandwich;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
